### ISSUE TITLE
bary_batch() repeats map(bexp_fun, xs)

### ISSUE THREAD

**Issue by lutefiskhotdish** [asmove/pybary#42]
I think it might run faster if `bexp_fun()` gets applied to all the `xs` just once?

https://github.com/asmove/pybary/blob/856d818d41fe6e35fa61af89360c41f75a516fef/pybary/pybary.py#L45C1-L49C1

Instead of
```
    coord_value_iter = zip(map(bexp_fun, xs), xs)
    num = reduce(sum_func, map(prod_func, coord_value_iter), zeros(size_x).T)

    den = reduce(sum_func, map(bexp_fun, xs), 0)

    return num / den
```
something like this might be sufficient:
```
    x_weights = [bexp_fun(x) for x in xs]
    barycenter = np.average(np.array(xs), axis=0, weights=np.array(x_weights))
    return barycenter
```

**Comment by brunolnetto** [comment]
@lutefiskhotdish I pushed a PR with your suggestion. Thanks! :)

**Comment by lutefiskhotdish** [comment]
Cool!  Interesting algorithm.

**Comment by lutefiskhotdish** [comment]
I think `bary_recur_formula()` could be defined *inside* `bary_recursive()`, then `bary_recur_formula()` would not need any parameters, which are just being passed through from the scope of `bary_recursive()`.  It might be slightly faster to not pass the parameters?  Maybe a bit tidier?  Just a thought.

**Comment by lutefiskhotdish** [comment]
Also, `lambda_ * m_1` happens twice in `bary_recur_formula()`.  Could save it into a variable the first time and avoid the second multiplication.  Very slight performance boost maybe?

**Comment by brunolnetto** [comment]
Both are nice ideas. I will implement as soon I tame the example fix in another example. Keep up! ;P

**Comment by brunolnetto** [comment]
@lutefiskhotdish my original intention was to expose the step-iteration formula to user have a greater control over the library. I have another idea implementing a class oriented artifact, but I am not a great fun of all verbosity it adds, since I first learned programming in C.

**Comment by brunolnetto** [comment]
@lutefiskhotdish I ended up updating code with your suggestions. :-) I will close this issue for now.

**Comment by lutefiskhotdish** [comment]
@brunolnetto I see what you mean about exposing the step-iteration formula.  A class instance might nicely encapsulate the parameters that rarely change from one iteration to the next.  Indeed, that would also avoid passing in m_1 and xhat_1 every time, if you see what I mean.  I think this is a good use case for a class.  Thoughts?

**Comment by lutefiskhotdish** [comment]
@brunolnetto In `bary_batch()` the `xs` are usually a numpy array, not a list of lists (which didn't work last time I tried it).  The doc string says list of lists, which doesn't seem to be right.

**Comment by brunolnetto** [comment]
Class name: BarycenterMethod
initializer: 
    - parameters:dict (optional)
    - m_1:float (optional)
    - xhat:Array (optional)
properties: 
    - parameters:dict
    - m_1:float
    - xhat:Array
Methods: 
    - update_barycenter_recursive(x:Array)
    - update_barycenter_batch(x:Array) 
    - update_parameters(parameters: dict) (?)

**Comment by lutefiskhotdish** [comment]
The tests for oracle returning scalar maybe are overly sensitive.  I made a simple toy oracle that returned abs(sum(*x)), and set `xs = array([[1.,2.], [3., 4.]])`.  My oracle returned numpy.float64 or something, but that apparently didn't satisfy the test for `float`?

**Comment by lutefiskhotdish** [comment]
> Class name: BarycenterMethod

Not sure "Method" is appropriate as part of the name of the class, since method has a specific meaning for Python classes.  Maybe "Optimizer" or something?

**Comment by lutefiskhotdish** [comment]
> - xhat:Array (optional)

Here and elsewhere I wonder if it would be helpful to use meaningful variable names instead of sticking closely to the arbitrary variable names and diacritics used in the original math formulas.

**Comment by brunolnetto** [comment]
May you as contributor push a PR, or several if needed? It is welcoming. :)

**Comment by brunolnetto** [comment]
> The tests for oracle returning scalar maybe are overly sensitive. I made a simple toy oracle that returned abs(sum(*x)), and set `xs = array([[1.,2.], [3., 4.]])`. My oracle returned numpy.float64 or something, but that apparently didn't satisfy the test for `float`?

May you refer the code line or url where this happens? I really do not remember making a readthedocs for this library. 😅

**Comment by brunolnetto** [comment]
> The tests for oracle returning scalar maybe are overly sensitive. I made a simple toy oracle that returned abs(sum(*x)), and set `xs = array([[1.,2.], [3., 4.]])`. My oracle returned numpy.float64 or something, but that apparently didn't satisfy the test for `float`?

Please, copy the example use case between triple quote ```. I can add something like below:

``` 
types= (float, numpy.half, numpy.single, float, numpy.double, numpy.longdouble)
if not isinstance(oracle(x0), types)
```

**Comment by lutefiskhotdish** [comment]
Sample that produces an error:
```
    from operator import add
    import numpy as np
    def oracle(x):
        return np.abs(add(*x))

    # xs = [np.array([1.,2.]), np.array([3.,4.])]
    xs = np.array([
        [1.,2.],
        [3.,4.]])

    print(oracle(xs[0]))
    # 3.0

    x = bary_recursive(oracle, xs)
    # Error
```

Maybe check that it's either *not* a sequence *or* is a sequence of length 1?  For checking sequence this might help:  https://stackoverflow.com/questions/16807011/python-how-to-identify-if-a-variable-is-an-array-or-a-scalar#16807050

**Comment by brunolnetto** [comment]
I was awaiting abc collections. I am not disappointed. xD

**Comment by lutefiskhotdish** [comment]
Actually, it looks like that doesn't work.  I'll look some more at testing for a scalar.

**Comment by brunolnetto** [comment]
@lutefiskhotdish I pushed your improvements to main code. In case you have further improvements and use cases, please, make me aware or send a PR.
